# Azure Dev CLI environment configuration for production

name: octocat-supply-prod
infra:
  provider: bicep
  path: infra
  module: main

pipeline:
  provider: github

services:
  api:
    project: ./api
    language: typescript
    host: appservice
    docker:
      path: ./api/Dockerfile

  frontend:
    project: ./frontend
    language: typescript
    host: staticwebapp
    docker:
      path: ./frontend/Dockerfile
    dist: dist

variables:
  # Infrastructure
  location: eastus
  environmentName: prod
  baseName: octocat-supply
  useRbacAuthorization: true
  
  # App Service 
  appServicePlanSku:
    name: S1
    tier: Standard
    size: S1
    family: S
    capacity: 2
    
  # Static Web App
  staticWebAppSku: Standard
